"""agent keys and events

Revision ID: 02a57acb0a3c
Revises: e660951855c0
Create Date: 2026-08-18 20:51:28.598208
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a57acb0a3c'
down_revision: str | None = 'e660951855c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_keys_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_keys_token_hash'), ['token_hash'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=True),
    sa.Column('camera_name', sa.String(length=120), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('clip_path', sa.String(length=512), nullable=True),
    sa.Column('clip_content_type', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_events_person_id'))
        batch_op.drop_index(batch_op.f('ix_events_kind'))
        batch_op.drop_index(batch_op.f('ix_events_camera_id'))

    op.drop_table('events')
    with op.batch_alter_table('agent_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_keys_token_hash'))
        batch_op.drop_index(batch_op.f('ix_agent_keys_tenant_id'))

    op.drop_table('agent_keys')
    # ### end Alembic commands ###
