"""camera defaults

Revision ID: 072cd4737715
Revises: 5bd38b7c7f14
Create Date: 2026-09-02 17:19:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072cd4737715'
down_revision: str | None = '5bd38b7c7f14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera_defaults',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('stream_path', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera_defaults')
    # ### end Alembic commands ###
